apiVersion: v2
name: dbtether
description: A Kubernetes operator for managing PostgreSQL databases in external clusters
type: application
version: 0.2.7
appVersion: "0.2.7"
keywords:
  - postgresql
  - postgres
  - database
  - operator
  - kubernetes
  - aurora
  - rds
  - dbtether
maintainers:
  - name: dbtether
    url: https://github.com/certainty3452/dbtether
sources:
  - https://github.com/certainty3452/dbtether

